options:
    additional-debian-packages:
        description: |
            Additional debian packages to install (eg. python-django-south). This
            string will be passed to apt-get.
        type: string
        default: ''
    additional-pip-packages:
        description: |
            Additional python packages that are not yet available as Ubuntu/Debian
            packages.
        type: string
        default: ''
    package-installation-directory:
        description: |
            The directory to install any provided packages in this config.
        type: string
        default: '/home/server-packages'
    re-install-mysql-server:
        description: |
            Set this to 'true' (or non-empty), if you wish to have mysql removed and purged
            from the instance. This happens when django-rainbow service is destroyed
            and then re-deloyed. Leave empty for false and keep any old settings.
        type: string
        default: ''
    purge-instance:
        description: |
            Set this to 'true' (or non-empty), if you wish to have all packages
            purged and re-installed. This includes any additional packages that are
            listed above or have been installed previously. This happens when
            django-rainbow service is destroyed and then re-deloyed. Leave empty for
            false and keep any old settings.
            --------------------------------------------------------------------
            DOES NOT INCLUDE MYSQL! If you wan't to re-install mysql than set
            the "re-install-mysql-server" to true.
        type: string
        default: 'true'
    run-update-upgrade:
        description: |
            Set this to 'true' (or non-empty), if you wish to run a apt-get update
            and upgrade. This is not recomended. Best to leave the Ubuntu version
            in the hands of the Juju team.   
        type: string
        default: ''

