options:
    revision:
        description: |
            The revision number of this file.            
        type: string
        default: '1'
    rainbow-packages:
        description: |
            The standard and basic packages for django-rainbow. These
            only include what is needed for a basic Django web server and
            operation of this charm. Others can be added below. 
        type: string
        default: apache2 python-mysqldb libapache2-mod-wsgi git mercurial pwgen python-pip python-setuptools
    apt-get-packages:
        description: |
            Debian packages to install (eg. python-django-south). This
            string will be passed to apt-get.
        type: string
        default: ''
    pip-packages:
        description: |
            These will be passed to pip install.
        type: string
        default: ''
    tar-packages:
        description: |
            These need to contain either source code with a configure file,
            or a python package with a setup.py file. These URLs need to conatain a 
            file with tar compession. You can use either tar, gzip (tar.gz), or bzip2 (tar.bz2)
            compressed files. Seperate urls with a space.
            Note: you can change the Django version here.
        type: string
        default: 'https://www.djangoproject.com/download/1.4/tarball'
    bzr-packages:
        description: |
            These need to contain either source code with a configure file,
            or a python package with a setup.py file. Seperate urls with a space.
        type: string
        default: ''
    git-packages:
        description: |
            These need to contain either source code with a configure file,
            or a python package with a setup.py file. Seperate urls with a space.
        type: string
        default: ''
    hg-packages:
        description: |
            These need to contain either source code with a configure file,
            or a python package with a setup.py file. Seperate urls with a space.
        type: string
        default: ''
    rainbow-installation-directory:
        description: |
            The directory that Django-rainbow will use to store data. This included
            packages, logs, and installation settings.
        type: string
        default: '/var/lib/django-rainbow'
    re-install-mysql-server:
        description: |
            Set this to true (or non-empty), if you wish to have the mysql client core removed
            and purged from the instance. This will effectively remove and replace the mysql root password.
            with a random one. This should not remove the database, but no garenties!
            This executes when django-rainbow service is destroyed and then re-deloyed or the install
            hook is re-triggerd. Leave empty for false.
        type: string
        default: ''
    purge-instance:
        description: |
            Set this to true (or non-empty), if you wish to have all packages
            purged and re-installed. This includes any additional packages that are
            listed above or have been installed previously. Do this if you have added
            any packages with dependantcy issues native to this charm.
            This executes when django-rainbow service is destroyed and then re-deloyed
            or the install hook is re-ran. 
            Leave empty for false. 
            ---------------------------------------------------------------------
            DOES NOT INCLUDE MYSQL! If you want to re-install the mysql client
            than set the re-install-mysql-server to true.
            ---------------------------------------------------------------------
        type: string
        default: 'true'
    project-repo-type:
        description: |
            ! ( Change this in the your-project.yaml file to utilize multiple projects on one instance )
            This is the brand of repository versioning the project uses. Only hg for now...
            E.g. bzr, hg, git, svn, etc...
        type: string
        default: ''
    project-repo-url:
        description: |
            The url of the project repository. Only bitbucket is supported currently.
            E.g. https://bitbucket.org/ubernostrum/django-registration
                 ssh://user@your-site.com/project
        type: string
        default: ''
    project-repo-username:
        description: |
            The username of the project repository.
        type: string
        default: ''
    project-repo-password:
        description: |
            The password of the project repository.
        type: string
        default: ''
    project-site-name:
        description: |
            (Optional) This is the name given to the site. It is used with emailing and
            running multiple sites toupled togther. Can be changed with the Django Admin system later.
            This option will be ignored if your do not have django.contrib.sites and a SITE_ID
            specified in the settings.py file.
        type: string
        default: ''
    project-site-domain:
        description: |
            (Optional) This is the domian given to the site. It is used with emailing and
            running multiple sites toupled togther. Can be changed with the Django Admin system later.
            This option will be ignored if your do not have django.contrib.sites and a SITE_ID
            specified in the settings.py file.
        type: string
        default: ''
    always-update-database: 
        description: |
            (Optional) Setting this option to non-empty will force a project database sync.
            If empty, the project database will only update when the settings.py file is modified
            from the current time stamp. 
        type: string
        default: ''
    always-update-sites-framework: 
        description: |
            (Optional) Setting this option to non-empty will always update the project-site-name
            and project-site-domain options from these yaml files into the django.sites framework.
            Set this to empty and only the intial options from the first run of the config-changed
            hook will be loaded. After that, the sites settings can be altered in the Django 
            Admin console. This can be set later as well.
        type: string
        default: ''
    project-apache2-vhost:
        description: |
            The entire virtual host for this django project. This will be place in a individual
            file and loaded with a2ensite.
        type: string
        default: ''

