options:
    additional-debian-packages:
        description: |
            Additional debian packages to install (eg. python-django-south). This
            string will be passed to apt-get.
        type: string
        default: ''
    additional-pip-packages:
        description: |
            Additional python packages that are not yet available as Ubuntu/Debian
            packages.
        type: string
        default: ''
    re-install-mysql-server:
        description: |
            Set this to true if you wish to have mysql removed and purged
            from the instance. Happens when django-rainbow service is destroyed
            and then re-deloyed. Leave empty for false and to keep old settings.
        type: string
        default: ''

