#!/bin/bash

# Created by Robert Edward Steckroth II, RobertSteckroth@gmail.com

set -eux # -x for verbose logging to juju debug-log

juju-log "Starting installation of Django-rainbow"

additional_debian_packages=`config-get additional_debian_packages`
additional_pip_packages=`config-get additional_pip_packages`
reinstall_mysql=`config-get re-install-mysql-server`


if [ "$additional_debian_packages" ]; then
    juju-log "Installing extra debian packages: $additional_debian_packages"
    sudo apt-get -y install $additional_debian_packages
fi

if [ "$additional_pip_packages" ]; then
    juju-log "Installing extra pip packages: $additional_pip_packages"
    sudo pip install $additional_pip_packages
fi

if ! [ -e "/var/lib/juju/" ]; then
       mkdir /var/lib/juju/
fi

if ! [ -e "/home/packages" ]; then
       mkdir /home/packages
fi


cd /home/packages

juju-log "Installing apache2 apache-wsgi and python dependencies via apt-get"

apt-get -y install apache2 python-mysqldb libapache2-mod-wsgi git mercurial
apt-get install -qqy debconf-utils pwgen


if ! [ -e "Django-1.4" ]; then 
       wget https://www.djangoproject.com/download/1.4/tarball
       tar -xvf tarball
       python Django-1.4/setup.py install
fi

# Install Django registration. Can be commented out at next if statment
# Needs to be in the stripe charm
# This copy is revised to work with Django 1.4
# Do not use official one on Bitbucket
if ! [ -e "django-registration" ]; then 
       wget http://www.pbdefence.com/static/files/django-registration.tar.bz2
       tar xvf django-registration.tar.bz2
       python django-registration/setup.py install
fi

juju-log "Checking for package mysql-server..."
if ( dpkg -s mysql-server | grep installed 2> /dev/null ); then
     juju-log "...installed"
     package="installed"
else
     package=""
     juju-log "...not installed"
fi 


if [ -z "$package" -o -n "$reinstall_mysql" ]; then
     if [ -n "$package" ]; then
          juju-log "Removing mysql-server, client, and all settings"
          apt-get -qqy purge mysql-client-core-5.5 mysql-server 
     fi
     juju-log "Installing mysql-server and client"
     apt-get -y install mysql-client-core-5.5
   # Generate a strong password for the mysql service, using /dev/urandom
     PASSWORD=`pwgen 10 1`
   # Store the password for later use by the db-relation-changed hook for this service unit.
     echo $PASSWORD > /var/lib/juju/mysql.passwd
     echo mysql-server-5.1 mysql-server/root_password password $PASSWORD | debconf-set-selections
     echo mysql-server-5.1 mysql-server/root_password_again password $PASSWORD | debconf-set-selections
     juju-log "mysql-server settings preseeded, now installing via apt-get"
     DEBIAN_FRONTEND=noninteractive apt-get -y install -qq mysql-server
     juju-log "Editing my.cnf to allow listening on all interfaces"
     sed --in-place=old 's/127\.0\.0\.1/0.0.0.0/' /etc/mysql/my.cnf
   # juju-log "Stopping mysql service"
   # service mysql stop
fi



a2dissite default

/etc/init.d/apache2 restart


